<div id="hello-message" class="hide">
    <div class="c header">
        <p class="uc c">Zapraszamy do wzięcia udziału w konkursie</p>
        <h1 class="uc">Odkryj Małopolskę</h1>
    </div>

    <div class="hr"></div>

    <p>Aby wziąć udział w konkursie należy <strong>polubić</strong> naszą stronę i odpowiedzieć na 10 quizowych pytań związanych z Małopolską. Niektóre z nich są zagadkami dźwiękowymi, więc włącz głośniki!</p>
    <p><strong>Do wygrania atrakcyjne nagrody</strong></p>
    <p class="c">
        <span class="btn-start blure">Weź udział w konkursie</span>
    </p>
</div>

<div id="begin-message" class="hide">
    <div class="c header">
        <p class="uc c">Zapraszamy do wzięcia udziału w konkursie</p>
        <h1 class="uc">Odkryj Małopolskę</h1>
    </div>

    <div class="hr"></div>

    <p>Każde z pytań jest warte 200 punktów, a na odpowiedź na każde z nich masz 20 sekund. Z każdą sekundą ubywa z puli 10 punktów, także spiesz się z odpowiedzią!</p>

    <p class="c">
        <a class="btn-start" onclick="fb_login()">Weź udział w konkursie</a>
    </p>
</div>

<div id="invite-message" class="hide">
    <div class="c header">
        <h2>Wyniki</h2>
    </div>

    <div class="hr"></div>

    <div id="results"></div>

    <p>Jeśli chcesz poprawić swój wynik <a onclick="sendRequestViaMultiFriendSelector();">zaproś trójkę znajomych</a> i weź udział w quizie ponownie</p>
    <a class="btn-start-again" onclick="sendRequestViaMultiFriendSelector(); return false;" href="<?php echo $this->url('app', array('action' => 'start'))?>"></a>
    <p class="c"><a class="show-awards-messege">Zobacz nagrody jakie możesz wygrać</a></p>
</div>

<div id="awards-messege" class="hide">

    <div class="c header">
        <h2>Nagrody</h2>
    </div>

    <div class="hr"></div>

    <div id="awards"></div>

    <p class="c"><a class="show-awards-messege">Zobacz nagrody jakie możesz wygrać</a></p>
</div>

<div id="play-box" class="hide">
    <div class="c">
        <h2 class="uc" id="question_title"></h2>
    </div>

    <div class="hr"></div>

    <div id="question"></div>

    <div id="answers"></div>
</div>

<?php
    if ($this->isAuth && !$this->canPlay) {
        $this->plugin('InlineScript')->appendScript('$quiz.auto_start = false;');
        $this->plugin('InlineScript')->appendScript('setTimeout($quiz.actions.showResults(), 1000);');
    }
?>