<div id="hello-message" class="hide">
    <div class="c header">
        <p class="uc c">Zapraszamy do wzięcia udziału w konkursie</p>
        <h1 class="uc">Odkryj Małopolskę</h1>
    </div>

    <div class="hr"></div>

    <p>Aby wziąć udział w konkursie należy <strong>polubić</strong> naszą stronę i odpowiedzieć na 10 quizowych pytań związanych z Małopolską. Niektóre z nich są zagadkami dźwiękowymi, więc włącz głośniki!</p>
    <p><strong>Do wygrania atrakcyjne nagrody</strong></p>
    <p class="c">
        <span id="auth-action" class="btn-start" onclick="fb_login()">Weź udział w konkursie</span>
        <span id="like-action-mock" class="btn-start blure">Weź udział w konkursie</span>
    </p>
    <p class="extra_small"><small>Biorąc udział w konkursie Odkryj Małopolskę akceptujesz regulamin konkursu. Pełny tekst regulaminu znajduje się <a target="_blank" href="Regulamin.pdf">tutaj</a>.<br/>
              Ta promocja nie jest sponsorowana, administrowana, ani zorganizowana przez Facebook. Dołączając do konkursu przekazujesz swoje prywatne informacje Organizatorowi. Informacje te zostaną wykorzystane tylko do celów promocyjnych zabawy.</small></p>
</div>

<div id="begin-message" class="hide">
    <div class="c header">
        <p class="uc c">Zapraszamy do wzięcia udziału w konkursie</p>
        <h1 class="uc">Odkryj Małopolskę</h1>
    </div>

    <div class="hr"></div>

    <p>Każde z pytań jest warte 200 punktów, a na odpowiedź na każde z nich masz 20 sekund. Z każdą sekundą ubywa z puli 10 punktów, także spiesz się z odpowiedzią!</p>

    <p class="c">
        <a class="btn-start" onclick="fb_login()">Weź udział w konkursie</a>
    </p>
    <p class="extra_small"><small>Biorąc udział w konkursie Odkryj Małopolskę akceptujesz regulamin konkursu. Pełny tekst regulaminu znajduje się <a target="_blank" href="Regulamin.pdf">tutaj</a>.<br/>
              Ta promocja nie jest sponsorowana, administrowana, ani zorganizowana przez Facebook. Dołączając do konkursu przekazujesz swoje prywatne informacje Organizatorowi. Informacje te zostaną wykorzystane tylko do celów promocyjnych zabawy.</small></p>
</div>

<div id="invite-message" class="hide">
    <div class="c header">
        <h2>Wyniki</h2>
    </div>

    <div class="hr"></div>

    <div id="results"></div>

    <p>W najbliższą niedzielę (<?php echo date('d.m', mktime(0,0,0, date('m'), date('d') + (7-date('N')), date('y')))?>) pierwsze 30 osób z rankingu otrzyma od nas zestawy nagród.</p>
    <p>Jeśli chcesz poprawić swój wynik <a onclick="sendRequestViaMultiFriendSelector();">zaproś trójkę znajomych</a> i weź udział w quizie ponownie</p>
    <a class="btn-start-again" onclick="sendRequestViaMultiFriendSelector(); return false;" href="<?php echo $this->url('app', array('action' => 'start'))?>"></a>
    <p class="c"><a class="show-awards-messege">Zobacz nagrody jakie możesz wygrać</a></p>
</div>

<div id="awards-messege" class="hide">

    <div class="c header">
        <h2>Nagrody</h2>
    </div>

    <div class="hr"></div>

    <div id="awards"></div>

    <p class="c"><a class="show-awards-messege">Zobacz nagrody jakie możesz wygrać</a></p>
</div>

<div id="play-box" class="hide">
    <div class="c">
        <h2 class="uc" id="question_title"></h2>
    </div>

    <div class="hr"></div>

    <div id="question"></div>

    <div id="answers"></div>
</div>

<?php
    if ($this->isAuth)
    {
        if ($this->canPlay) {
            $this->plugin('InlineScript')->appendScript('$quiz.is_auth_and_can_play = true;');
        } else {
            $this->plugin('InlineScript')->appendScript('$quiz.auto_start = false;');
            $this->plugin('InlineScript')->appendScript('$quiz.is_auth_and_cant_play = true;');
            $this->plugin('InlineScript')->appendScript('setTimeout($quiz.actions.showResults(), 1000);');
        }
    }
?>