<div class="c header">
    <p class="uc c">Zapraszamy do wzięcia udziału w konkursie</p>
    <h1 class="uc">Odkryj Małopolskę</h1>
</div>

<div class="hr"></div>

<p>Aby wziąć udział w konkursie należy <strong>polubić</strong> naszą stronę i odpowiedzieć na 10 quizowych pytań związanych z Małopolską. Niektóre z nich są zagadkami dźwiękowymi, więc włącz głośniki!</p>

<!--<p>Każde z pytań jest warte 200 punktów, a na odpowiedź na każde z nich masz 20 sekund. Z każdą sekundą ubywa z puli 10 punktów, także spiesz się z odpowiedzią!</p>-->

<p><strong>Do wygrania atrakcyjne nagrody</strong></p>

<p class="c">
    <a class="btn-start" href="<?php echo $this->url('app', array('action' => 'start'))?>">Weź udział w konkursie</a>
</p>