<div class="c">
    <h2 class="uc">Jaki zamek widać na filmie?</h2>
</div>

<div class="hr"></div>


<div id="question">
    <iframe width="340" height="203" src="http://www.youtube.com/embed/6cv9H0m0v3o?autoplay=1" frameborder="0" allowfullscreen></iframe>
</div>


<div id="answers">
    <ul class="answers">
        <li>Wawel</li>
        <li>Zamek w Nowym Sączu</li>
        <li>Zamek w Targu Nowotarskim</li>
    </ul>
</div>