<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<head>
<!--
    Author: Gabriel Habryn
    Email: widmogrod@gmail.com
    Created: 2011-11
-->
<?php
    echo $this->plugin('HeadTitle');
    echo $this->plugin('HeadMeta');
    echo $this->plugin('HeadMeta');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
?>
</head>
<body>
<div id="container">
    <div id="header">

    </div>
    <div id="wrapper">
        <div id="main">
            <?php echo $this->raw('content') ?>
        </div>
    </div>
    <div id="footer">
        
    </div>
</div>
</body>
</html>