<?php echo $this->plugin('doctype')->setDoctype(\Zend\View\Helper\Doctype::HTML5); ?>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
    <meta charset="utf-8">
    <?php
        echo $this->plugin('HeadTitle');
        echo $this->plugin('HeadMeta');
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
    ?>
</head>
<body>
<div id="fb-root"></div>
<div id="container">
    <div id="header">
        <span class="fl question question-number"><span id="question-no">Pytanie 1</span></span>
        <span class="fr question question-time"><span id="question-time">00:20</span></span>
    </div>
    <div id="wrapper">
        <div id="loader"></div>
        <div id="messager"></div>
        <div id="main">

            <?php echo $this->raw('content') ?>
        </div>
    </div>
    <div id="footer">
        <!-- none -->
    </div>
</div>
<?php
    echo $this->plugin('InlineScript');
?>
</body>
</html>