<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo BASE_URI?>">
    <?php
        echo $this->plugin('HeadTitle');
        echo $this->plugin('HeadMeta');
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
    ?>
</head>

<body>

<div class="topbar">
    <div class="fill">
        <div class="container">
            <a class="brand" href="#">Quiz</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="content">
        <div class="row">
            <div class="span14">
                <div class="well" style="padding: 16px 19px;">
                    <a class="btn small primary"
                       href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizlist')) ?>">Zarządzaj
                        pytaniami</a>
                    <a class="btn small primary"
                       href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizmanage')) ?>">Dodaj</a>
                    <a class="btn small primary"
                       href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizusers')) ?>">Użytkownicy</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="span14">
                <?php echo $this->raw('content'); ?>
            </div>
        </div>
    </div>
</div>
<!-- /container -->

<?php
    echo $this->plugin('InlineScript');
?>

</body>
</html>

