<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <base href="<?php echo BASE_URI?>">
    <?php
        echo $this->plugin('HeadTitle');
        echo $this->plugin('HeadMeta');
        echo $this->plugin('HeadLink');
        echo $this->plugin('HeadStyle');
        echo $this->plugin('HeadScript');
    ?>
</head>

<body>

<div class="topbar" data-scrollspy="scrollspy">
    <div class="fill">
        <div class="container">
            <a class="brand" href="#">Quiz</a>
            <ul class="nav">

                <li class="dropdown" data-dropdown="dropdown">
                    <a href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizlist')) ?>" class="dropdown-toggle">Pytania</a>
                    <ul class="dropdown-menu" >
                        <li><a href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizlist')) ?>">Zarządzaj pytaniami</a></li>
                        <li><a href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizmanage')) ?>">Dodaj pytanie</a></li>
                    </ul>
                </li>

                <li><a href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizusers')) ?>">Użytkownicy</a></li>
                <li><a href="<?php echo $this->url('default', array('controller' => 'quizadmin', 'action' => 'quizresults')) ?>">Wyniki</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    <div class="content">
        <div class="row">
            <div class="span14">
                <?php echo $this->raw('content'); ?>
            </div>
        </div>
    </div>
</div>
<!-- /container -->

<?php
    echo $this->plugin('InlineScript');
?>

</body>
</html>

