<?php

namespace Quiz\Repository;

use Doctrine\ORM\EntityRepository;
use Quiz\Entity;

/**
 * Question
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question extends EntityRepository
{
    public function create(array $data)
    {
        $question = new Entity\Question();
        $question->setTitle($data['title']);
        $question->setContent($data['content']);
        $question->setType($data['type']);

        foreach($data['answers'] as $answerNo => $answerName)
        {
            $isCorrect = (isset($data['correct']) && $data['correct'] == $answerNo);

            $answer = new Entity\Answer();
            $answer->setName($answerName);
            $answer->setIsCorrect($isCorrect);
            $question->addAnswer($answer);
        }

        $em = $this->getEntityManager();
        $em->persist($question);

        try {
            $em->flush();
        } catch (\Exception $e) {
            var_dump(__METHOD__.__LINE__);
            var_dump($e->getMessage());
        }
    }
}