<?php

namespace Quiz\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Quiz
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quiz extends EntityRepository
{
    public function getQuestions()
    {
        $dql = 'SELECT q, a FROM Quiz\Entity\Question q JOIN q.answers a';


        /** @var $q  \Doctrine\ORM\QueryBuilder */
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setMaxResults(10);

        $result = array();

        try {
            $result = $q->getArrayResult();
        } catch (\Exception $e) {
            
        }

        /*
         * DQL do not allowe me to sqlect only a.name and a.id and mantaine array structure.
         */
        foreach($result as &$question)
        {
            foreach($question['answers'] as &$answer)
            {
                unset($answer['isCorrect']);
            }
        }

        return $result;
    }
}