<?php

namespace Quiz\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User extends EntityRepository
{
    public function createFacebookUser($facebookId, array $data)
    {
        $user = $this->findOneBy(array('facebookId' => $facebookId));
        if (!$user)
        {
            $user = new \Quiz\Entity\User();
            $user->setFacebookId($facebookId);
        }

        // sprintf('https://graph.facebook.com/%s/picture', $data['username'])
        $user->setUsername($data['username']);

        if (isset($data['first_name']) && isset($data['last_name'])) {
            $user->setFullname(sprintf('%s %s', $data['first_name'] , $data['last_name']));
        }

        $em = $this->getEntityManager();

        try
        {
            $em->persist($user);
            $em->flush();
        } catch (\Exception $e) {
            # todo log
            return false;
        }

        return $user;
    }

    public function saveAnswers($facebookId, array $answers)
    {
        foreach($answers as $answer)
        {
//            $answers = new \Quiz\Entity\QuizAnswer();
//            $answers->setAnswer();
//            $answers->setQuiz();
//            $answers->setSecond();
        }
    }

    public function getResults()
    {
        $dql = 'SELECT q, a FROM Quiz\Entity\Question q JOIN q.answers a';


        /** @var $q  \Doctrine\ORM\QueryBuilder */
        $q = $this->getEntityManager()->createQuery($dql);
        $q->setMaxResults(10);

        $result = array();

        try {
            $result = $q->getArrayResult();
        } catch (\Exception $e) {

        }

        return $result;
    }
}